name: Master to Test Promotion

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  promote_master_to_test:
    name: Master branch'in test branch'ine aktarılması
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu indirme
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git kullanıcı bilgisinin ayarlanması
        run: |
          git config user.name "furk4nyildiz"
          git config user.email "fmyildiz41@gmail.com"

      - name: Master değişikliklerinin test branch'ine merge edilmesi
        run: |
          git fetch origin

          # Test branch'ine geç
          git checkout test

          # Master'ı test'e merge et
          git merge --no-ff origin/master -m "master değişikliklerinin test branch'ine aktarılması"

          # Sonuçları remote test branch'ine gönder
          git push origin test
